Fix su exit codes and environment filtering
memorysafety/sudo-rs pull request #518
Opened 2023-06-21 19:56 UTC by marlonbaeten

Fixes #502
Fixes #503
Fixes #504 
Fixes #505 
Fixes #507

2023-06-22 11:54 UTC, japaric requested changes
this breaks a compliance test that was passing

2023-06-22 11:54 UTC, japaric commented on test-framework/sudo-compliance-tests/src/su/flag_shell.rs
> +        format!("su: failed to execute /does/not/exist: No such file or directory")
clippy complains about these `format!` calls. either you could store the string "/does/not/exist" in a variable and use string interpolation here (and also use the variable in the `Command` call above); or you could switch these to string literals

2023-06-22 11:54 UTC, japaric commented on src/su/context.rs
> +        let mut environment = if options.login || !options.preserve_environment {
I don't think this is correct. `su` does *not* clear the environment when `--preserve-environment`. `man su` says:

>        -m, -p, --preserve-environment
>           Preserve the entire environment, i.e., do not set HOME, SHELL, USER or LOGNAME. This option is ignored if the option --login is specified.

which I think means that only `HOME`, `SHELL`, `USER` and `LOGNAME` are not overwritten when the flag is used.

I think is reason why the `su::env::vars_in_invoking_users_env_are_preserved` test no longer passes with this PR.

2023-06-22 14:12 UTC, japaric commented on src/su/context.rs
> +        let mut environment = if options.login || !options.preserve_environment {
created a new issue for this #529

2023-06-22 14:32 UTC, japaric requested changes

2023-06-22 14:32 UTC, japaric commented on build.rs
> +    // TODO: use _PATH_STDPATH and _PATH_DEFPATH_ROOT from paths.h
this breaks some existing sudo tests:
``` console
    env_reset::some_vars_are_set
    env_reset::user_dependent_vars
    env_reset::vars_whose_values_start_with_parentheses_are_removed
```

I think sudo and su have different default PATH values

2023-06-27 08:33 UTC, rnijveld approved these changes

2023-06-27 09:05 UTC, merged